# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 086b3179cda53e309888d66d6915f8be96bc1e23b043e72de9e8a1bcdd847288cc35a33106ba1c049e8e583d57cbefb391c8af458c39e944e80c30ddcdd80164

test:
  secret_key_base: cc5d6d6d9145fd8f28003841d5d9866d2b025b9b4582838d71639a870856b13ff2339362c92f0a25c74d3829e3434a9a3635a20673ff3c042168f0b227dfee65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
